### ISSUE TITLE
V1 contains breaking changes and switch on node20, even tough it should not

### ISSUE THREAD

**Issue by morapet** [tibdex/github-app-token#89]
https://github.com/tibdex/github-app-token/commit/388799afab39cbab3f3423723006d78c87a49cfb - this should not be part of tag v1 right? seems like all release point to some wired commits.

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node20' is not supported, use 'docker', 'node12' or 'node16' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)

**Comment by morapet** [comment]
resolved by https://github.com/tibdex/github-app-token/issues/87
