### ISSUE TITLE
Post job cleanup - Error: Could not revoke installation access token 

### ISSUE THREAD

**Issue by GoranHalvarsson** [tibdex/github-app-token#98]
Hello
The workflow is going well until, the **post job cleanup**

I get this weird error, in Post job cleanup.

Any idea why I get this error?
```
 Error: Could not revoke installation access token.
     at revokeInstallationAccessToken (file:///D:/a/_actions/tibdex/github-app-token/v2/dist/post/index.js:7:70955)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async file:///D:/a/_actions/tibdex/github-app-token/v2/dist/post/index.js:7:70644
     at async run (file:///D:/a/_actions/tibdex/github-app-token/v2/dist/post/index.js:7:71110)
     at async file:///D:/a/_actions/tibdex/github-app-token/v2/dist/post/index.js:7:70457 {
   [cause]: RequestError [HttpError]: Bad credentials
       at file:///D:/a/_actions/tibdex/github-app-token/v2/dist/post/index.js:1:45703
       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
       at async revokeInstallationAccessToken (file:///D:/a/_actions/tibdex/github-app-token/v2/dist/post/index.js:7:70894)
       at async file:///D:/a/_actions/tibdex/github-app-token/v2/dist/post/index.js:7:70644
       at async run (file:///D:/a/_actions/tibdex/github-app-token/v2/dist/post/index.js:7:71110)
       at async file:///D:/a/_actions/tibdex/github-app-token/v2/dist/post/index.js:7:70457 {
     status: 401,
     response: {
       url: 'https://api.github.com/installation/token',
       status: 401,
       headers: [Object],
       data: [Object]
     },
     request: {
       method: 'DELETE',
       url: 'https://api.github.com/installation/token',
       headers: [Object],
       request: [Object]
     }
   }
 } 
```

**Comment by djthornton1212** [comment]
I too have recently begun to see this error.

```shell
Post job cleanup.
Error: Could not revoke installation access token.
    at revokeInstallationAccessToken (file:///home/runner/work/_actions/tibdex/github-app-token/v[2](https://github.com/caregility/iconsult_front_end/actions/runs/6584797783/job/17889996736#step:28:2).1.0/dist/post/index.js:7:70955)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/runner/work/_actions/tibdex/github-app-token/v2.1.0/dist/post/index.js:7:70644
    at async run (file:///home/runner/work/_actions/tibdex/github-app-token/v2.1.0/dist/post/index.js:7:71110)
    at async file:///home/runner/work/_actions/tibdex/github-app-token/v2.1.0/dist/post/index.js:7:70457 {
  [cause]: RequestError [HttpError]: Bad credentials
      at file:///home/runner/work/_actions/tibdex/github-app-token/v2.1.0/dist/post/index.js:1:4570[3](https://github.com/caregility/iconsult_front_end/actions/runs/6584797783/job/17889996736#step:28:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async revokeInstallationAccessToken (file:///home/runner/work/_actions/tibdex/github-app-token/v2.1.0/dist/post/index.js:7:7089[4](https://github.com/caregility/iconsult_front_end/actions/runs/6584797783/job/17889996736#step:28:4))
      at async file:///home/runner/work/_actions/tibdex/github-app-token/v2.1.0/dist/post/index.js:7:70644
      at async run (file:///home/runner/work/_actions/tibdex/github-app-token/v2.1.0/dist/post/index.js:7:71110)
      at async file:///home/runner/work/_actions/tibdex/github-app-token/v2.1.0/dist/post/index.js:7:704[5](https://github.com/caregility/iconsult_front_end/actions/runs/6584797783/job/17889996736#step:28:5)[7](https://github.com/caregility/iconsult_front_end/actions/runs/6584797783/job/17889996736#step:28:7) {
    status: 401,
    response: {
      url: 'https://api.github.com/installation/token',
      status: 401,
      headers: [Object],
      data: [Object]
    },
    request: {
      method: 'DELETE',
      url: 'https://api.github.com/installation/token',
      headers: [Object],
      request: [Object]
    }
  }
}
```

**Comment by tibdex** [comment]
You can set `revoke` to `false`:

https://github.com/tibdex/github-app-token/blob/3eb77c7243b85c65e84acfa93fdbac02fb6bd532/README.md?plain=1#L46-L47

**Comment by GoranHalvarsson** [comment]
Ah thanks!!BrGöran Halvarsson20 okt. 2023 kl. 16:13 skrev Thibault Derousseaux ***@***.***>:﻿
You can set revoke to false:
https://github.com/tibdex/github-app-token/blob/3eb77c7243b85c65e84acfa93fdbac02fb6bd532/README.md?plain=1#L46-L47
